#!/usr/bin/env python3
"""Regenerate the bundled outlines with fonttools==4.60.1.

Usage: uv run --with fonttools==4.60.1 python scripts/prepare-font.py FONT.ttf OFL.txt
Source: https://github.com/google/fonts/tree/main/ofl/archivoblack
Only needed when regenerating assets; normal SVG/HTML builds use Node alone.
"""
import hashlib
import json
import re
import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

source, license_path = map(Path, sys.argv[1:])
digest = hashlib.sha256(source.read_bytes()).hexdigest()
if digest != "dd9a89a019b4849f66ab75455fe7bdf931311042cbb0f0f97acc061539703180":
    raise ValueError("Unexpected Archivo Black font revision; review before updating outlines.")
font = TTFont(source)
glyphs = font.getGlyphSet()
# Match the original PRO's cap height, retaining the font's natural proportions.
scale = 129 / font["OS/2"].sCapHeight
transform = (scale, 0, 0, -scale, 0, 129)
outlines = {}
for code, name in sorted(font.getBestCmap().items()):
    glyph = glyphs[name]
    path = SVGPathPen(glyphs, ntos=lambda n: format(round(n, 3), "g"))
    bounds = BoundsPen(glyphs)
    glyph.draw(TransformPen(path, transform))
    glyph.draw(TransformPen(bounds, transform))
    commands = []
    for command, numbers in re.findall(r"([A-Za-z])([^A-Za-z]*)", path.getCommands()):
        if command not in "MLHVQCZ":
            raise ValueError(f"Unexpected outline command: {command}")
        commands.append([command, *map(float, re.findall(r"-?\d+(?:\.\d+)?", numbers))])
    outlines[str(code)] = [glyph.width * scale, bounds.bounds, commands]

license_text = "\n".join(line.rstrip() for line in license_path.read_text().splitlines()).strip()
output = Path(__file__).resolve().parent.parent / "assets" / "archivo-black.mjs"
output.write_text(
    "// Generated by scripts/prepare-font.py; do not edit by hand.\n"
    f"// Font SHA-256: {digest}\n"
    "// Each glyph: [advance, ink bounds (left, top, right, bottom), absolute SVG commands].\n"
    "/*\n" + license_text + "\n*/\n"
    "export const ARCHIVO_BLACK = {\n" + ",\n".join(
        f'  "{code}":' + json.dumps(glyph, separators=(",", ":"))
        for code, glyph in outlines.items()
    ) + "\n};\n"
)
print(f"Wrote {len(outlines)} glyphs to {output} ({output.stat().st_size} bytes)")
